version: '3'
services:

  auth:
    build: .
    image: speedro/auth_service
    container_name: auth.speedro
    hostname: auth.speedro
    ports:
      - "8083:8083"
    networks:
      - auth
      - consul_consul
      - postgres_postgres_pedro

networks:
  auth:
  consul_consul:
    external: true
  postgres_postgres_pedro:
    external: true
