version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres.devspot
    hostname: postgres.devspot
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
      - DB_NAME=users
      - TZ=Europe/Prague
    volumes:
      - ./dbinit.sh:/docker-entrypoint-initdb.d/dbinit.sh
      - postgres_devspot:/var/lib/postgresql/data/
    networks:
      postgres_devspot:

  auth:
    build: .
    image: speedro/auth_service
    container_name: auth.speedro
    hostname: auth.speedro
    ports:
      - "8083:8083"
    networks:
      - auth
      - postgres_devspot
    depends_on:
      - postgres

networks:
  auth:
  postgres_devspot:

volumes:
  postgres_devspot:
