spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users-test
    username: auth-docker
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 8093
