spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: auth-docker
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml

server:
  port: 8083
