spring:

  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres:5432/users
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 8083

management:
  server:
    port: 4453

email:
  service: normal
