spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:users-test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-test.yaml
  cloud:
    consul:
      enabled: false
      discovery:
        enabled: false
server:
  port: 8083
