version: '3'
services:

  auth:
    image: pedro_cze/auth_service
    container_name: auth.pedro_cze
    hostname: auth.pedro_cze
    ports:
      - "8083:8083"
    networks:
      - auth
      - consul_consul
      - postgres_postgres_pedro

networks:
  auth:
  consul_consul:
    external: true
  postgres_postgres_pedro:
    external: true
